import { IDaybatchResponse, IDaybatchSettings, IInstallQuestionnaire, IInstallQuestionnaireResponse, IQuestionnaire, IQuestionnaireSettings, ISurveyDays } from "../interfaces/questionnaires.interface";
export declare const QuestionnaireListMockObject: IQuestionnaire[];
export declare const QuestionnaireMockObject: IQuestionnaire;
export declare const InstallQuestionnaireMockObject: IInstallQuestionnaire;
export declare const InstallQuestionnaireResponseMockObject: IInstallQuestionnaireResponse;
export declare const QuestionnaireSettingsMockList: IQuestionnaireSettings[];
export declare const QuestionnaireDaybatchCasesMock: IDaybatchResponse[];
export declare const AddDaybatchMock: IDaybatchSettings;
export declare const SurveyDaysMock: string[];
export declare const SurveyDaysDatesMock: ISurveyDays;
