import BlaiseApiClient from "../blaise-api-client";
import { IDaybatchResponse, IDaybatchSettings, IInstallQuestionnaire, IInstallQuestionnaireResponse, IQuestionnaire, IQuestionnaireSettings, ISurveyDays } from "../interfaces/questionnaires.interface";
export declare function getAllQuestionnairesWithCatiData(this: BlaiseApiClient): Promise<IQuestionnaire[]>;
export declare function getQuestionnairesWithCatiData(this: BlaiseApiClient, serverpark: string): Promise<IQuestionnaire[]>;
export declare function getQuestionnaireWithCatiData(this: BlaiseApiClient, serverpark: string, questionnaireName: string): Promise<IQuestionnaire>;
export declare function getQuestionnaires(this: BlaiseApiClient, serverpark: string): Promise<IQuestionnaire[]>;
export declare function questionnaireExists(this: BlaiseApiClient, serverpark: string, questionnaireName: string): Promise<boolean>;
export declare function doesQuestionnaireHaveMode(this: BlaiseApiClient, serverpark: string, questionnaireName: string, mode: string): Promise<boolean>;
export declare function getQuestionnaire(this: BlaiseApiClient, serverpark: string, questionnaireName: string): Promise<IQuestionnaire>;
export declare function installQuestionnaire(this: BlaiseApiClient, serverpark: string, questionnaire: IInstallQuestionnaire): Promise<IInstallQuestionnaireResponse>;
export declare function deleteQuestionnaire(this: BlaiseApiClient, serverpark: string, questionnaireName: string): Promise<null>;
export declare function getQuestionnaireCaseIds(this: BlaiseApiClient, serverpark: string, questionnaireName: string): Promise<string[]>;
export declare function getQuestionnaireModes(this: BlaiseApiClient, serverpark: string, questionnaireName: string): Promise<string[]>;
export declare function getQuestionnaireSettings(this: BlaiseApiClient, serverpark: string, questionnaireName: string): Promise<IQuestionnaireSettings[]>;
export declare function activateQuestionnaire(this: BlaiseApiClient, serverpark: string, questionnaireName: string): Promise<null>;
export declare function deactivateQuestionnaire(this: BlaiseApiClient, serverpark: string, questionnaireName: string): Promise<null>;
export declare function getDaybatch(this: BlaiseApiClient, serverpark: string, questionnaireName: string): Promise<IDaybatchResponse>;
export declare function addDaybatch(this: BlaiseApiClient, serverpark: string, questionnaireName: string, daybatchSettings: IDaybatchSettings): Promise<IDaybatchResponse>;
export declare function getSurveyDays(this: BlaiseApiClient, serverpark: string, questionnaireName: string): Promise<string[]>;
export declare function addSurveyDays(this: BlaiseApiClient, serverpark: string, questionnaireName: string, surveyDays: ISurveyDays): Promise<string[]>;
