---
name: ✅ Run CI Validation
permissions:
    contents: read
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
jobs:
    run-ci-validation:
        runs-on: ubuntu-latest
        steps:
            - name: 🛎️ Checkout Repository
              uses: actions/checkout@v6
            - name: 🔧 Setup Node and Cache
              uses: actions/setup-node@v6
              with:
                  node-version: 24.x
                  cache: yarn
            - name: 📦 Install Dependencies
              # TODO: remove network-concurrency after yarn upgrade
              # run: yarn install --frozen-lockfile --network-concurrency 1
              run: yarn install --frozen-lockfile # check...
            - name: 🧹 Run Linter
              run: yarn lint
            - name: 🧪 Run Tests and Generate Coverage
              run: yarn test
